"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Task = { title: string; course: string; deadline: string; estimatedMinutes: number };
export function TaskExtractor({ onApplied }: { onApplied: () => Promise<void> }) {
  const [tasks, setTasks] = useState<Task[]>([]), [questions, setQuestions] = useState<string[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function extract(form: HTMLFormElement) {
    setBusy(true); setError("");
    try { const data = new FormData(form); data.set("mode", "tasks"); const response = await fetch("/api/study/extract", { method: "POST", body: data }), result = await response.json(); if (!response.ok) throw new Error(result.error); setTasks(result.tasks); setQuestions(result.questions); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "识别失败"); } finally { setBusy(false); }
  }
  return <section className="space-y-3 rounded-xl bg-[var(--color-surface-hover)] p-4"><h2 className="font-medium">从老师要求提取任务</h2><form className="space-y-3" onSubmit={event => { event.preventDefault(); void extract(event.currentTarget); }}><textarea name="text" aria-label="老师的作业要求" placeholder="粘贴作业要求；若提取结果需要确认，可补充日期等信息后重新识别。" maxLength={100000} className="min-h-24 w-full rounded-md bg-[var(--color-surface)] p-3 text-sm" /><input type="file" name="file" aria-label="上传作业要求" accept="image/*,.pdf,.doc,.docx,.ppt,.pptx,.md,.txt" /><Button variant="secondary" disabled={busy} type="submit">{busy ? "正在识别…" : "识别并预览"}</Button></form>{questions.map((question, index) => <p key={index} className="text-sm text-[var(--color-accent)]">需要补充：{question}</p>)}{tasks.map((task, index) => <div key={index} className="space-y-2 rounded-lg bg-[var(--color-surface)] p-3"><Input aria-label={`识别任务${index + 1}名称`} value={task.title} onChange={event => setTasks(previous => previous.map((t, i) => i === index ? { ...t, title: event.target.value } : t))} /><p className="text-xs">北京时间 {new Date(task.deadline).toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" })} · 预计 {task.estimatedMinutes} 分钟</p><Button variant="ghost" disabled={busy} onClick={() => setTasks(previous => previous.filter((_, i) => i !== index))}>移除</Button></div>)}{tasks.length > 0 && <Button disabled={busy} onClick={async () => { setBusy(true); setError(""); const remaining = [...tasks]; try { while (remaining.length) { const response = await fetch("/api/study/tasks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(remaining[0]) }); if (!response.ok) throw new Error((await response.json()).error); remaining.shift(); setTasks([...remaining]); } await onApplied(); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存失败"); } finally { setBusy(false); } }}>确认并保存 {tasks.length} 个任务</Button>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</section>;
}
